python3 run_train.py \
  --model_name_or_path neuralmind/bert-base-portuguese-cased \
  --dataset_name tiagoblima/punctuation-nilc \
  --output_dir tiagoblima/punctuation-nilc-bert-base \
  --do_train \
  --do_eval \
  --do_predict \
  --push_to_hub \
  --num_train_epochs 5 \
  --use_auth_token \
  --report_to wandb